# This is a basic workflow to help you get started with Actions

name: startGAV2ray

on: 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '* */6 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: ssh vps
        env:
          SAKURAFRP_ADDR: ${{secrets.SAKURAFRP_ADDR}}
          UUID: ${{secrets.UUID}}
          SERVERPUSHKEY: ${{secrets.SERVERPUSHKEY}}
          SAKURAFRP_URL: ${{secrets.SAKURAFRP_URL}}
        run: ./tmate2actions.sh
        shell: bash
